[project]
name = "dotfiles-sync"
version = "0.1.0"
description = "Simple tool to synchronize dotfiles across machines"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathspec>=0.12.1",
]
